### ISSUE TITLE
npm install fails with  Error: Cannot find module 'node-uuid'

### ISSUE THREAD

**Issue by yarikoptic** [ReproNim/brainverse#115]
following CONTRIBUTING.md:
```shell
hopa:~/proj/repronim
$> git clone git://github.com/ReproNim/brainverse.git     
Cloning into 'brainverse'...
remote: Counting objects: 2571, done.
remote: Compressing objects: 100% (146/146), done.
remote: Total 2571 (delta 168), reused 209 (delta 118), pack-reused 2305
Receiving objects: 100% (2571/2571), 4.10 MiB | 1.08 MiB/s, done.
Resolving deltas: 100% (1483/1483), done.
2 19533.....................................:Tue 16 Jan 2018 04:13:23 PM EST:.
hopa:~/proj/repronim
$> cd brainverse 
CONTRIBUTING.md  README.md  eapp/    package-lock.json  src/    yarn.lock
LICENSE          build/     main.js  package.json       tests/
2 19534.....................................:Tue 16 Jan 2018 04:13:25 PM EST:.
(git)hopa:~/proj/repronim/brainverse[master]
$> npm install
module.js:538
    throw err;
    ^

Error: Cannot find module 'node-uuid'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/nodejs/request/index.js:29:12)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

$> acpolicy npm
npm:
  Installed: 1.4.21+ds-2
  Candidate: 1.4.21+ds-2
  Version table:
 *** 1.4.21+ds-2 600
        600 http://http.debian.net/debian sid/main amd64 Packages
        600 http://http.debian.net/debian sid/main i386 Packages
        100 /var/lib/dpkg/status
```

**Comment by yarikoptic** [comment]
interestingly I have node uuid module installed:
```shell
$> apt-cache policy node-node-uuid                                         
node-node-uuid:                    
  Installed: 1.4.7-1
  Candidate: 1.4.7-1
  Version table:
 *** 1.4.7-1 600
        600 http://http.debian.net/debian sid/main amd64 Packages
        600 http://http.debian.net/debian sid/main i386 Packages
        100 /var/lib/dpkg/status
     1.4.0-1 100
        100 http://http.debian.net/debian stretch/main amd64 Packages
        100 http://http.debian.net/debian stretch/main i386 Packages
```
