### ISSUE TITLE
Build Error with electron-builder

### ISSUE THREAD

**Issue by smpadhy** [ReproNim/brainverse#89]
When trying to build using npm run electron-builder, following error occurs and builds fails
electron-builder 19.43.0
Rebuilding native production dependencies for darwin:x64
Packaging for darwin x64 using electron 1.4.13 to dist/mac
Error: EISDIR: illegal operation on a directory, read
    at w (/Users/smruti/gitrepo/brainverse/node_modules/electron-builder/src/asar/asarUtil.ts:191:11)
    at writeStream.write (/Users/smruti/gitrepo/brainverse/node_modules/electron-builder/src/asar/asarUtil.ts:193:43)
    at afterWrite (_stream_writable.js:454:3)
    at onwrite (_stream_writable.js:445:7)
    at fs.js:2182:5
    at FSReqWrap.wrapper [as oncomplete] (fs.js:687:5)

**Comment by smpadhy** [comment]
Deleted previous packaged app and used yarn dist. 
Was able to build without error.

**Comment by smpadhy** [comment]
Also electron-builder does not recommend use of npm.
